// Die 89 Edelsteine von Fame – Stufe 1 (Malachit) bis Stufe 89 (Diamant).
//
// cut:  Brillant-Familie: round, oval, cushion, cushionSquare, marquise, pear, princess, radiant,
//       radiantSquare – Treppenschliffe: emerald (ratio = Länge zu Breite, corner = Eckenschräge),
//       asscher, octagon – cabochon (gewölbt, ohne Facetten) – rough (Rohdiamant).
//       Typischer Schliff je Stein: siehe CUTS unten. Oval, Kissen und Birne kennen ebenfalls ratio.
// look: clear (durchsichtig), milk (milchig), opaque (undurchsichtig mit Muster),
//       opal (Farbspiel), labra (Farbschimmer), moon (bläulicher Schimmer), star (Sternstein),
//       diamond (der Diamant)
// pattern (für Cabochons): bands, clouds, flecks, dendrite, matrix, glitter, veins
// c = Hauptfarbe, c2 = zweite Farbe (Muster, Bicolor, Farbwechsel)

const G = (name, c, cut = 'brilliant', look = 'clear', extra = {}) => ({ name, c, cut, look, ...extra });

export const GEM_LIST = [
  G('Malachit', '#1c8a4a', 'cabochon', 'opaque', { pattern: 'bands', c2: '#0b3f22' }),
  G('Larimar', '#5cc4e2', 'cabochon', 'opaque', { pattern: 'clouds', c2: '#eefcff' }),
  G('Mondstein', '#d6e2f4', 'cabochon', 'moon'),
  G('Chalzedon', '#86a3cf', 'cabochon', 'milk'),
  G('Lapislazuli', '#1f3aa0', 'cabochon', 'opaque', { pattern: 'flecks', c2: '#e8c25a' }),
  G('Dendritenachat', '#d6cfc0', 'cabochon', 'opaque', { pattern: 'dendrite', c2: '#2a2622' }),
  G('Rauchquarz', '#6e5440'),
  G('Chrysopras', '#47c27a', 'cabochon', 'milk'),
  G('Sonnenstein', '#e07a32', 'cabochon', 'opaque', { pattern: 'glitter', c2: '#ffd08a' }),
  G('Weißtopas', '#f2f6fb', 'oval'),
  G('Rosenquarz', '#ee98b0', 'cabochon', 'milk'),
  G('Spektrolith', '#26323f', 'cabochon', 'labra', { c2: '#3fd0ff' }),
  G('Bergkristall', '#eef4fc'),
  G('Rutilquarz', '#efe6d0', 'oval', 'clear', { c2: '#d4a43a' }),
  G('Labradorit', '#36424e', 'cabochon', 'labra', { c2: '#3f8cff' }),
  G('Fibrolith', '#b3a998', 'cabochon', 'milk'),
  G('Swiss-Blue-Topas', '#4cc2ea'),
  G('Sky-Blue-Topas', '#a2dcf3', 'oval'),
  G('Prasiolith', '#b4e2a4', 'step'),
  G('Amethyst', '#9a56d2', 'oval'),
  G('London-Blue-Topas', '#1e5888'),
  G('Granat', '#8c1a1e'),
  G('Citrin', '#f2af38', 'step'),
  G('Naturblauer Topas', '#8ac8e6', 'oval'),
  G('Blautopas', '#3ea8e0'),
  G('Skapolith', '#f0d878', 'oval'),
  G('Diopsid', '#2e6a3a'),
  G('Champagner-Topas', '#e6c79a', 'step'),
  G('Fluorit', '#8f7ee0', 'step', 'clear', { c2: '#6ad49e', bicolor: true }),
  G('Kyanit', '#2c5db8', 'oval'),
  G('Chromdiopsid', '#1b7a3c'),
  G('Koroit-Boulder-Opal', '#5a3a22', 'cabochon', 'opal', { c2: '#3a2414' }),
  G('Goldberyll', '#f0be3e', 'step'),
  G('Iolith', '#4a4eb2', 'oval'),
  G('Achroit', '#f4f6f0', 'step'),
  G('Beryll', '#c6e6d0', 'step'),
  G('Welo-Opal', '#f0e4cc', 'cabochon', 'opal', { c2: '#fff4e0' }),
  G('Sugilith', '#6a2a8c', 'cabochon', 'opaque', { pattern: 'clouds', c2: '#3a1450' }),
  G('Rhodolith', '#b0284e'),
  G('Türkis', '#3ec8c0', 'cabochon', 'opaque', { pattern: 'matrix', c2: '#5a4834' }),
  G('Kunzit', '#f2b6dc', 'step'),
  G('Andalusit', '#8a6a3a', 'oval', 'clear', { c2: '#5c7a36', bicolor: true }),
  G('Titanit', '#c6d43a'),
  G('Morganit', '#f6c0b2', 'step'),
  G('Peridot', '#9cca38', 'oval'),
  G('Rhodonit', '#d2567a', 'cabochon', 'opaque', { pattern: 'veins', c2: '#1e1a1a' }),
  G('Siberit', '#c2185a', 'step'),
  G('Apatit', '#2ec4c6'),
  G('Sternsaphir', '#34489a', 'cabochon', 'star'),
  G('Rubellit', '#d81b5e', 'step'),
  G('Yowah-Boulder-Opal', '#6a4426', 'cabochon', 'opal', { c2: '#40281a' }),
  G('Bicolor-Turmalin', '#e8507a', 'step', 'clear', { c2: '#4caf50', bicolor: true }),
  G('Turmalin', '#3a8a5a', 'step'),
  G('Verdelith', '#2e7d32', 'step'),
  G('Goldtopas', '#f5a523', 'oval'),
  G('Boulder-Opal', '#4a3020', 'cabochon', 'opal', { c2: '#2a1a10' }),
  G('Hessonit', '#c8641e'),
  G('Zirkon', '#a6dcf2'),
  G('Aquamarin', '#7fd4e8', 'step'),
  G('Opal', '#eae6e0', 'cabochon', 'opal', { c2: '#ffffff' }),
  G('Pyrop', '#9a0f1e'),
  G('Spessartin', '#ff6a14'),
  G('Indigolith', '#1a3e8a', 'step'),
  G('Feueropal', '#ff781a', 'oval'),
  G('Crystal Opal', '#dce6ee', 'cabochon', 'opal', { c2: '#f4f8fc' }),
  G('White Opal', '#f2f0ec', 'cabochon', 'opal', { c2: '#ffffff' }),
  G('Chrysoberyll', '#d6d23a', 'oval'),
  G('Imperial-Topas', '#f08824', 'step'),
  G('Chromturmalin', '#0f8a3a', 'step'),
  G('Sternrubin', '#b0102c', 'cabochon', 'star'),
  G('Spinell', '#e0204a'),
  G('Black Crystal Opal', '#1e2026', 'cabochon', 'opal', { c2: '#0e1014' }),
  G('Gelber Saphir', '#ffd21e', 'oval'),
  G('Tansanit', '#4b3ec2', 'oval'),
  G('Semi Black Opal', '#3a3c44', 'cabochon', 'opal', { c2: '#24262c' }),
  G('Tsavorit', '#1eae4a'),
  G('Jeremejewit', '#8ecff0', 'oval'),
  G('Black Opal', '#121318', 'cabochon', 'opal', { c2: '#08090c' }),
  G('Grüner Saphir', '#2e8e5a', 'oval'),
  G('Padparadscha-Saphir', '#ff9a7a', 'oval'),
  G('Demantoid', '#5ed03a'),
  G('Violetter Saphir', '#8a3ed2', 'oval'),
  G('Saphir', '#1d3ebf', 'oval'),
  G('Rosa Saphir', '#ff6eae', 'oval'),
  G('Smaragd', '#0f9a5a', 'step', 'clear'),
  G('Rubin', '#d40f3a', 'oval', 'clear'),
  G('Alexandrit', '#2f8a6a', 'brilliant', 'clear', { c2: '#a02e6a', shift: true }),
  G('Paraíba-Turmalin', '#1ee2e0', 'oval', 'clear', { glow: true }),
  G('Diamant', '#ffffff', 'round', 'diamond'),

  // Die Legenden: berühmte Diamanten ab 300.000 € bis 1 Mio. €
  G('Orangefarbener Diamant', '#f7a01a', 'pear', 'diamond', { legend: true }),
  G('The Unique Pink', '#ff7d8c', 'pear', 'diamond', { legend: true }),
  G('De Beers Millennium Jewel 4', '#8ea8ec', 'oval', 'diamond', { legend: true, ratio: 1.38 }),
  G('Fancy Intense Pink', '#f6b3d0', 'cushion', 'diamond', { legend: true, ratio: 1.22 }),
  G('Blue Moon of Josephine', '#2a62e8', 'cushion', 'diamond', { legend: true, ratio: 1.36 }),
  G('Pink Legacy', '#f98db2', 'emerald', 'diamond', { legend: true, ratio: 1.2, corner: 0.32 }),
  G('Oppenheimer Blue', '#3f6cb4', 'emerald', 'diamond', { legend: true, ratio: 1.48, corner: 0.14 }),
  G('The Constellation', '#ffffff', 'rough', 'diamond', { legend: true }),
  G('Lesedi La Rona', '#ffffff', 'asscher', 'diamond', { legend: true, ratio: 1.04, corner: 0.27 }),
  G('The Pink Star', '#f78aa2', 'oval', 'diamond', { legend: true, ratio: 1.3 }),
];

// Typischer Schliff je Stein (für alle facettierten Steine außer den Legenden)
const CUTS = {
  'Rauchquarz': 'cushion', 'Weißtopas': 'round', 'Bergkristall': 'radiant', 'Rutilquarz': 'cushion',
  'Swiss-Blue-Topas': 'cushionSquare', 'Sky-Blue-Topas': 'oval', 'Prasiolith': 'octagon', 'Amethyst': 'oval',
  'London-Blue-Topas': 'emerald', 'Granat': 'round', 'Citrin': 'cushionSquare', 'Naturblauer Topas': 'marquise',
  'Blautopas': 'princess', 'Skapolith': 'oval', 'Diopsid': 'round', 'Champagner-Topas': 'emerald',
  'Fluorit': 'octagon', 'Kyanit': 'emerald', 'Chromdiopsid': 'cushionSquare', 'Goldberyll': 'emerald',
  'Iolith': 'cushion', 'Achroit': 'asscher', 'Beryll': 'emerald', 'Rhodolith': 'cushion',
  'Kunzit': 'radiant', 'Andalusit': 'oval', 'Titanit': 'round', 'Morganit': 'pear', 'Peridot': 'oval',
  'Siberit': 'emerald', 'Apatit': 'radiantSquare', 'Rubellit': 'cushion', 'Bicolor-Turmalin': 'emerald',
  'Turmalin': 'radiant', 'Verdelith': 'emerald', 'Goldtopas': 'pear', 'Hessonit': 'oval', 'Zirkon': 'round',
  'Aquamarin': 'emerald', 'Pyrop': 'round', 'Spessartin': 'cushionSquare', 'Indigolith': 'emerald',
  'Feueropal': 'oval', 'Chrysoberyll': 'cushion', 'Imperial-Topas': 'pear', 'Chromturmalin': 'octagon',
  'Spinell': 'cushion', 'Gelber Saphir': 'radiant', 'Tansanit': 'cushionSquare', 'Tsavorit': 'round',
  'Jeremejewit': 'oval', 'Grüner Saphir': 'asscher', 'Padparadscha-Saphir': 'cushion', 'Demantoid': 'round',
  'Violetter Saphir': 'marquise', 'Saphir': 'oval', 'Rosa Saphir': 'pear', 'Smaragd': 'emerald',
  'Rubin': 'cushion', 'Alexandrit': 'cushion', 'Paraíba-Turmalin': 'pear',
};

// Ein eigener Spruch für jede Card: frech, in der Sprache der Feeds – sagt dir, wie fame du bist
const SAYINGS = {
  'Malachit': 'Erster Stein, erste Aura. Lowkey ein Flex.',
  'Larimar': 'Karibik-Vibes für ’nen Fünfer. Das crazy.',
  'Mondstein': 'Leuchtet nachts. Du auch, no cap.',
  'Chalzedon': 'Chill-Aura aktiviert. Respekt, Bro.',
  'Lapislazuli': 'Blau mit Gold drin – it’s giving Königsdrip.',
  'Dendritenachat': 'Ein ganzer Wald im Stein. Du bist der Main Character.',
  'Rauchquarz': 'Rauchig, mysteriös, lowkey zu cool.',
  'Chrysopras': 'Frisch wie dein Glow-up.',
  'Sonnenstein': 'Sonne geht auf, Aura geht hoch.',
  'Weißtopas': 'Clean. Clear. Iconic.',
  'Rosenquarz': 'Soft Era, harter Flex.',
  'Spektrolith': 'Alle Farben, null NPC-Energie.',
  'Bergkristall': 'Klarer als dein Plan fürs Wochenende.',
  'Rutilquarz': 'Goldfäden im Glas. Drip seit der Steinzeit.',
  'Labradorit': 'Erst unscheinbar, dann: sheesh.',
  'Fibrolith': 'Kennt keiner. Genau das ist der Flex.',
  'Swiss-Blue-Topas': 'Alpen-Vibes, Gipfel-Aura.',
  'Sky-Blue-Topas': 'Sky is not the limit. Du bist es.',
  'Prasiolith': 'Grün vor Neid sind die anderen. W.',
  'Amethyst': 'Lila Era unlocked. Assignment verstanden.',
  'London-Blue-Topas': 'Dunkelblau wie dein Nachtleben. Wild.',
  'Granat': 'Tiefrot und loyal – ein echter Ehrenstein.',
  'Citrin': 'Gelb, gut gelaunt, gönnt sich.',
  'Naturblauer Topas': 'Natural Glow. Kein Filter nötig.',
  'Blautopas': 'Nicht blau gemacht. Blau geflext.',
  'Skapolith': 'Den kennt kaum einer. Du schon. Goated.',
  'Diopsid': 'Dunkelgrün mit Tiefgang. Real talk.',
  'Champagner-Topas': 'Champagner-Laune, ganz ohne Kater.',
  'Fluorit': 'Zwei Farben, ein Vibe. Slay.',
  'Kyanit': 'Blau mit Ecken und Kanten – wie du.',
  'Chromdiopsid': 'Sibirisch kalt, aber heiß begehrt.',
  'Koroit-Boulder-Opal': 'Feuerwerk im Gestein. Sheesh!',
  'Goldberyll': 'Gold, das nicht protzen muss. Tut’s trotzdem.',
  'Iolith': 'Wikinger-Kompass. Richtung: nur nach oben.',
  'Achroit': 'Farblos? Eher fehlerlos.',
  'Beryll': 'Smaragd-Familie. Du bist jetzt Cousin.',
  'Welo-Opal': 'Regenbogen to go. Der Vibe ist immaculate.',
  'Sugilith': 'So selten wie 80 % Akku am Abend.',
  'Rhodolith': 'Rosenrot und voll Rizz.',
  'Türkis': 'Pharaonen-Aura. Ägypten approved.',
  'Kunzit': 'Zartrosa, aber Main Character.',
  'Andalusit': 'Wechselt die Farbe, nie den Style.',
  'Titanit': 'Mehr Feuer als ein Diamant. Psst, nicht weitersagen.',
  'Morganit': 'Pfirsich, Rosé, pure Gönnung.',
  'Peridot': 'Im Vulkan geboren. Das crazy.',
  'Rhodonit': 'Rosa mit Tattoo-Linien. Hard.',
  'Siberit': 'Eiskalt aus Sibirien, heiß auf Insta.',
  'Apatit': 'Neonblau. Da scrollt keiner vorbei.',
  'Sternsaphir': 'Du trägst einen Stern. Kein Fake.',
  'Rubellit': 'Pink-Rot und komplett unbothered.',
  'Yowah-Boulder-Opal': 'Outback-Lore unlocked.',
  'Bicolor-Turmalin': 'Zwei Seiten, beide fire.',
  'Turmalin': 'Kann jede Farbe. Kann jeden Flex.',
  'Verdelith': 'Grün, glänzend, goated.',
  'Goldtopas': 'Golden Hour, aber für immer.',
  'Boulder-Opal': 'Feuer im Fels. Aura im Himmel.',
  'Hessonit': 'Zimt, Honig, Hauptcharakter.',
  'Zirkon': 'Älter als die Berge, frischer als dein Feed.',
  'Aquamarin': 'Ozean-Vibes. Die Wellen machst du selbst.',
  'Opal': 'Jeder Blick ein neuer Filter.',
  'Pyrop': 'Feuerrot. Nicht anfassen, zu heiß.',
  'Spessartin': 'Mandarinen-Drip. Saftig.',
  'Indigolith': 'Tiefblau und rar wie WLAN im Zug.',
  'Feueropal': 'Brennt, ohne zu verglühen. Du so: on fire.',
  'Crystal Opal': 'Klar wie Glas, bunt wie ein Festival.',
  'White Opal': 'Weiß, aber null basic.',
  'Chrysoberyll': 'Goldgrün und härter als dein Montag.',
  'Imperial-Topas': 'Für Zaren gemacht. Jetzt deine Era.',
  'Chromturmalin': 'Smaragdgrün mit eigenem Kopf. Unbothered.',
  'Sternrubin': 'Ein Stern in Rot. Mehr Fame geht kaum.',
  'Spinell': 'Früher Rubin-Double, heute selbst der Star.',
  'Black Crystal Opal': 'Dark Mode, aber in Farbe.',
  'Gelber Saphir': 'Sonnenschein mit Saphir-Härte. Unkaputtbar.',
  'Tansanit': 'Nur an einem Ort der Welt. Und jetzt bei dir.',
  'Semi Black Opal': 'Halb Nacht, ganz Feuerwerk.',
  'Tsavorit': 'Grüner als der Neid der anderen. Easy W.',
  'Jeremejewit': 'Kann keiner aussprechen. Will jeder haben.',
  'Black Opal': 'König der Opale. Und du der Endgegner.',
  'Grüner Saphir': 'Grün mit Saphir-Power. Built different.',
  'Padparadscha-Saphir': 'Sunset-Vibes in Stein. Ate.',
  'Demantoid': 'Funkelt feuriger als ein Diamant. Sorry, Diamant.',
  'Violetter Saphir': 'Violett, edel, absolute Aura.',
  'Saphir': 'Kronjuwelen-Energie. Du regierst.',
  'Rosa Saphir': 'Barbie-Pink mit Rückgrat.',
  'Smaragd': 'Grün vor Neid – die anderen. Du: chillst.',
  'Rubin': 'Red Carpet unter deinen Füßen. Sheesh.',
  'Alexandrit': 'Wechselt die Farbe, nie den Vibe.',
  'Paraíba-Turmalin': 'Leuchtet heller als jede Clubnacht.',
  'Diamant': 'Erst Fame, dann die anderen. Forever.',
  'Orangefarbener Diamant': 'Feuer in Tropfenform. Und du bist noch heißer.',
  'The Unique Pink': 'Unique wie du. Kein Dupe möglich.',
  'De Beers Millennium Jewel 4': 'Ein Jahrtausend-Stein. Dein Jahrtausend-Flex.',
  'Fancy Intense Pink': 'Intensiv. Wie dein Auftritt.',
  'Blue Moon of Josephine': 'Passiert einmal im blauen Mond. Also jetzt.',
  'Pink Legacy': 'Legacy unlocked. Die Lore schreibst du.',
  'Oppenheimer Blue': 'Das tiefste Blau. Die höchste Aura.',
  'The Constellation': 'Ein ganzes Sternbild – und du bist der hellste Stern.',
  'Lesedi La Rona': '„Unser Licht“ – jetzt deins. GOAT-Status.',
  'The Pink Star': 'Endgegner besiegt. Aura: unendlich.',
};

// Brechzahl und Farbaufspaltung ("Feuer") je Steinart – bestimmen, wie das Licht im Stein läuft.
const OPTICS = [
  [/Diamant|Pink|Blue|Jewel|Constellation|Lesedi/, 2.42, 0.024],
  [/Demantoid/, 1.89, 0.034],
  [/Titanit/, 1.95, 0.034],
  [/Zirkon/, 1.95, 0.022],
  [/Saphir|Rubin/, 1.77, 0.009],
  [/Granat|Pyrop|Spessartin|Rhodolith|Hessonit|Tsavorit/, 1.76, 0.012],
  [/Spinell|Chrysoberyll|Alexandrit/, 1.74, 0.01],
  [/Peridot|Diopsid|Kyanit|Tansanit|Jeremejewit/, 1.68, 0.01],
  [/Topas|Andalusit|Apatit/, 1.62, 0.008],
  [/Turmalin|Verdelith|Indigolith|Rubellit|Siberit|Achroit/, 1.63, 0.009],
  [/Smaragd|Aquamarin|Beryll|Morganit/, 1.58, 0.007],
];
for (const g of GEM_LIST) {
  if (SAYINGS[g.name]) g.flavor = SAYINGS[g.name];
  if (g.cut === 'cabochon') continue;
  if (CUTS[g.name]) g.cut = CUTS[g.name];
  const o = OPTICS.find(([re]) => re.test(g.name));
  g.ior = o ? o[1] : 1.55;
  g.disp = o ? o[2] : 0.007;
}
